import os
import sqlite3

dirname = os.path.dirname(__file__)
data_file = os.path.join(dirname, 'rules.db')

conn = sqlite3.connect(data_file)
cursor = conn.cursor()

sample_data = [
    (205,'''An adopted rule change takes full effect at the moment of the completion of the vote that adopted it.''',1),
    (206,'''When a proposed rule change is defeated, the player who proposed it loses 10 points.''',1),
    (207,'''Each player has exactly one vote.''',1),
    (208,'''The winner is the first person to achieve 100 (positive) points.''',1),
    (211,'''If two or more mutable rules conflict with one another, or if two or more immutable rules conflict with one another, then the rule with the lowest ordinal number takes precedence.

If at least one of the rules in conflict explicitly says of itself that it defers to another rule (or type or rule) or takes precedence over another rule (or type of rule), then such provisions shall supersede the numerical method for determining precedence.

If two or more rules claim to take precedence over one another or to defer to one another, then the numerical method must again govern.''',1),
    (212,'''If players disagree about the legality of a move or the interpretation or application of a rule, then the player preceding the one moving is to be the Judge and to decide the question. Disagreement, for the purposes of this rule, may be created by the insistence of any player. Such a process is called *invoking judgement*.

When judgement has been invoked, the next player may not begin his or her own turn without the consent of a majority of the other players.

The Judge's judgement may be overruled only by a unanimous vote of the other players, taken before the next turn is begun. If a Judge's judgement is overruled, the player preceding the Judge in the playing order becomes the new Judge for the question, except that no player is to be Judge during his own turn or during the turn of a teammate.

Unless a Judge is overruled, one Judge settles all questions arising from the game until the next turn is begun, including questions as to his or her own legitimacy and jurisdiction as Judge.

New Judges are not bound by the decisions of old Judges. New Judges may, however, settle only those questions on which the players currently disagree and that affect the completion of the turn in which judgement was invoked. All decisions by Judges shall be in accordance with all the rules then in effect; but when the rules are silent, inconsistent, or unclear on the point at issue, then the Judge's only guides shall be common morality, common logic, and the spirit of the game.''',1),
    (213,'''If the rules are changed so that further play is impossible, or if the legality of a move is impossible to determine with finality, or if by the Judge's best reasoning, not overruled, a move appears equally legal and illegal, then the first player who is unable to complete a turn is the winner.

This rule takes precedence over every other rule determining the winner.''',1),
    (301,'''The vote requirements for a rule change to be adopted is a simple majority in favor. All eligible voters who don't vote within the voting period automatically abstain.''',1),
    (304,'''Rule changes that transmute immutable rules into mutable rules may be adopted if and only if the vote is unanimous among the eligible voters.''',1),
    (307,'''This rule governs the addition and permissions of New Players.

A player may, at any point in the game, invite two or fewer people to join the game of Nomic by sending them a server invite. A player may do this no more than once every three rounds, and must announce the invitation, as well as the invited players, in the ⁠nomic-general channel.   
Once an invited player joins the server, they shall be added to the turn order four turns after the current turn. Additionally, they shall be granted points equal to 90% of the mean point value among other players, as well as the New Player role, which they will continue to hold until they have completed two turns, defining them as a New Player.  
As a turn action on their turn, a player may initiate a vote (in addition to their proposal) to remove one or more New Players from the game. In order to initiate this special vote, henceforth referred to as a Removal Vote, the initiating player must provide a reasonable and well-thought-out justification for the removal of those players.  
In order for a Removal Vote to pass, it must receive a 2/3 majority among players who are not New Players and did not invite any of the New Players being considered for removal. If the Removal Vote fails, the player who initiated it loses five points. If a removal vote passes, the removed New Players will be banned from the server. They may not be invited again. Should the original invitation of the removed players have been in bad faith, the player(s) who invited the removed players lose five points for each bad-faith invitation.

This rule takes priority over any other rule that governs the addition and permissions of New Players.''',1),
    (309,'''An Inactive List shall be created with 0 players. Players may leave the list at any time and may join the list if and only if two of the player's turns have ended since they last left the list. Players on the list shall have their turns automatically skipped at 24 hours after they are pinged to begin their turn unless they announce intention to finish the turn. Intention to leave/join the list or finish a turn shall be done in \\#nomic-official and shall be up for consensus interpretation.''',1),
    (311,'''Players shall alternate in a set order initially based on order of joining, taking one whole turn apiece. The order of turns wraps back to the first player after the last: This wrapping is called a turn cycle.  
Skipping a turn is the same as passing a turn.  
Turns may not be skipped unless another rule explicitly states as such, and parts of turns may not be omitted.  
Skipping a turn means that the skipped player's turn is delayed until the next turn cycle. If a player partially completes a turn but is skipped before fully completing it, they will complete only the remaining actions of the incomplete turn on the next turn cycle. (Example: if a New Player's turn is skipped, the skip does not count towards the two turns they need to complete to lose the New Player role until they complete the turn on a future turn cycle.)  
All players begin with zero points.''',1),
    (312,'''When a player proposes a rule change and the official vote is unanimous, that player rolls an additional d6 for points that turn.''',1),
    (313,'''A player creating a poll must use at least one word from a foreign language when creating the options for their poll''',1),
    (315,'''If a player fails to complete their turn within five days after they are notified that their turn has begun, any remaining portions of their turn are skipped and they are to be added to the Inactive Players list.''',1),
    (321,'''Players may not privately conspire or consult on the making of future rule changes unless they are teammates. If a player (Player A) provides ample evidence of another player (Player B) breaking this rule, then Player A gains 3 points and Player B loses 6 points.''',1),
    (322,'''If, at any point, a rule (Rule A) references another rule (Rule B) by ordinal number, and the ordinal number of rule B is altered for whatever reason, the text of rule A shall be altered to reference rule B by its new ordinal number. This alteration does not count as an amendment to rule A and does not have any effect on rule A's ordinal number.''',1),
    (323,'''This rule shall govern all aspects of the creation and usage of teams and shall take precedence over all other rules regarding teams. At any point in time, a player may create a team with one or more other players (with the consent of the other players). This team may contain up to (but not including) one half of the number of current players in the server. Any players in the same team are considered "teammates" throughout the existance of the team. Before any Nomic-related conspiring or conversation occurs in the team, one member of the team must announce the creation of the team and the identities of its members in either nomic-general or nomic-official. They may also include a team name, but it is not necessary. Upon the announcement of a team, the server admin must document the existence of the team, the team members, and the team name (if present) in nomic-rules. A team member may not leave a team until at least twenty-four hours after the creation of the team, and if they do leave afterwards, they must announce it in nomic-general or nomic-official so that it can be properly documented. One player may be in up to three distinct teams at once. A team, at any time, may privately conspire (using any means of communication other than this server) on the creation of a nomic proposal. If this occurs, and said proposal get submitted for debate or vote, it will be designated a "team-based proposal" and must be marked as such. Additionally, any points that are lost or gained by the submitter of a team-based proposal that are caused *directly* by the results of the vote (losing points if a vote fails, rolling a second die if a vote is unanimous, etc.) will operate in this manner: The submitter will still gain or lose the same number of points as normal, but an additional fifty percent of the points will be divided up amongst all other group members''',1),
    (324,'''As a turn action *once per turn*, a player (Player A) can challenge any subset of n-1 players (excluding Player A themselves), for n>1, to any game that all can play and takes a reasonable amount of time. If the game is finished, point changes will depend on the result of the game in accordance with the following rules: (a) Point changes shall be integers that scale linearly with position (1st, 2nd, 3rd, etc.). (b) Total point changes shall sum to zero. (c) The winner's point change shall be the smallest integer greater than 9 such that (a) and (b) are possible. (d) In the case of ties, the point changes of all tied players shall be the average of their tied positions. If the game is still ongoing or is never played by the time it is Player A's turn again, (Player A's turn again with no result), all players involved will lose ceiling(10/n) points. If any player declines, Player A may choose to follow-up by challenging the remaining players to the same game. If it is decided the game will not be played due to player count or otherwise, Player A gets max(0, 5-n) points. If this happens to 3 of Player A's challenges in a row, then they cannot challenge another player in their next turn.''',1),
    (325,'''Any action done by a player at any time that is considered illegal by common consensus (or by a Judge, see rule 212) shall be erased from all official records and considered null and void. Should the illegal action be a required turn action, the incurring player must redo that action or be at risk of having the rest of their turn skipped per rule 315. Additionally, if the incurring player has taken any other actions after the illegal action but before it is corrected, those subsequent actions shall also be considered null and void and, if the actions are required, will also need to be redone to complete said player's turn.

Additionally, a “wall of shame” which lists players and the number of illegal actions they have committed in a read-only Discord channel leaderboard #wall-of-shame with the number of violations they have committed next to their name shall be created.''',1),
    (327,'''Nonintiger points are rounded down if positive and up if negative.''',1),
    (328,'''If a player votes in any poll, official or not, they have the opportunity to write one and only one sonnet (14 lines, iambic pentameter, rhyme scheme of poet's choice) defending their position. Unless the argument presented in the sonnet is considered to be [a) irrelevant, b) illogical, c) purposefully offensive or demeaning to one or more people, whether they are players or not, or d) illegal according to the current rules of Nomic], then the poet's vote will count as double its normal value. **In order for the sonnet to be accepted, it must be submitted in nomic-general within the voting period.** Other than rule 207. which this takes precedence over, this does not replace any other rules regulating voting procedures, including what is currently known as rule 335; rather, it stacks with them.''',1),
    (329,'''This proposal regulates what laws, regardless of time or place, we will follow. Said laws must have actually existed in a country/state/province/a real place (Nomic rules or board game rules are not included in this proposal). *Getting caught* breaking any of the laws within this proposal will detract one point per offense. For what "laws" are, we will use the following definition: "The system of rules which a particular country or community recognizes as regulating the actions of its members and which it may enforce by the imposition of penalties, excluding Nomic rules." Law 1, from North Dakota: It is illegal to keep an elk in a sandbox in your backyard. No law, varying the compensation for the services of the Senators and Representatives, shall take effect, until an election of Representatives shall have intervened.''',1),
    (330,'''After the passing of one turn cycle (as defined in rule 311), a dx (where x is the number of players in the game at time of rolling) will be rolled. The xth player in the turn order will choose a player. The chosen player will have to incorporate a dictionary defined english word of the xth player's choosing in their next rule proposal. If the chosen player does not do this, they will suffer the consequences outlined in 325 as well as the loss of 5 points.''',1),
    (332,'''If you roll for points in nomic-rolls and get a 1 or a 7, you get to move the robber to a player. If a player has the robber, they are unable to acquire points in any way, shape, or form. Players with the robber can still lose points. If a player still has the robber after one full turn cycle has passed, the robber is moved to no player (Robber does not affect anyone) and is out of play until someone rolls a 1 or a 7 and can move it once more. Clarification; you cannot move the robber out of play, only into play. The robber can only get out of play from the one full turn cycle. You also still roll for points and play as usual, just do not gain those points.''',1),
    (333,'''This rule governs special events. It takes priority over all other rules relating to Special Events. If a player feels that an action not covered by the rules is necessary at any time, a player may propose a Special Event in the nomic-official channel by creating a poll with the ordinal number of the Special Event and its text. A player may do this no more than once per every two rounds.   
The special event takes an ordinal number equal to one plus the number of previous proposed Special Events. A special event written by a team is considered a team-based proposal. Play can progress while a Special Event is voted on, but no player may take actions that would alter the situation the Special Event is designed to address. If this stops a player from making progress on their turn, the duration of the Special Event's poll is excluded from the time limit of that player's turn. The proposed Special Event must pertain to something not covered by the rules and take the form of an action to be taken and/or paradigm to be adopted immediately after the success of the Special Event's associated poll. If the text of the event conflicts with a rule or a previous judge's ruling, the Event's poll is considered to have failed. 

The Special Event poll is conducted in the same manner as votes on proposals, with the following changes:

1. The Special Event Poll lasts 24 hours  
2. The Special Event Poll requires a 2/3 majority to pass. 

If the Special Event Poll fails, then the player who proposed it loses 10 points.''',1),
    (334,'''This rule shall govern all aspects of a Nomic mechanic which shall henceforth be known as "game hours." As such, it takes precedence over all other rules concerning game hours.

The game hours of this game of nomic shall start at 9:00 AM EST and end at 10:00 PM EST. This means that:

* All votes may only be timed during game hours. If a vote is created such that any part of its duration would take place outside game hours, those eleven hours will not count toward the time limit of the vote. (E.g; a vote started at 9:00 PM EST will end at 10:00 AM EST the next day, and a vote started at 3:00 AM EST will end at 11:00 AM EST.) Players may still vote outside of game hours, but any calculations to determine if a vote auto-passes (as detailed in rule 344) shall not be conducted until game hours resume.  
* Debate over a rule may take place at any time, during or outside of game hours, but debate conducted outside of game hours may not be counted toward the decision that there has been sufficient debate on a topic. The only exception to this is the following, and shall be named the "Wisdom of Sufficiency Clause":  
* If at least three separate messages are sent in nomic-debate outside of game hours regarding relevant debate over a proposal, and if no further messages are sent in nomic-debate over the span of the first two hours of the following set of game hours (until 11:00 AM EST), any player may create a poll in nomic-debate asking if there has been sufficient debate. If three players, not counting the player whose turn it is (or, if the proposal at hand is team-based, anybody on the proposing team) vote that there has been sufficient debate, then the player whose turn it is may decide to end debate and move to an official vote.  
* Any other actions that require a time commitment of any measure shall function in a similar manner: steps of that action may be taken outside of game hours, but no player shall be considered to have broken the rules of Nomic for not completing an action outside of the game hours.''',1),
    (335,'''Whenever a player wishes to vote 'nay' on any future proposal, they must post an audio recording in #nomic-debate of them reciting any song in full. Failure to comply before the poll ends will result in their vote being thrown out.''',1),
    (336,'''The robber gains robbed points.''',1),
    (338,'''This rule establishes the process for ratifying and adopting ambiguously-worded rules changes, henceforth referred to as "the ratification process."

When a proposal that does not directly cause a rules change, but rather provides for the adoption of an arbitrary rules change, is adopted, the rules shall not be changed immediately. Instead, some funny shit happens, as described below:

The player who proposed the triggering rules change, or anyone who both voted "yea" on said proposal and submitted a sonnet to endorse their vote, may propose text for the rules change to add to the official rules in nomic-debate. If multiple texts are proposed within a short timeframe, the most recent text proposed by the person who initially proposed the rule is considered to be the only legitimate text for the purpose of this rule. New texts cannot be proposed once significant action has been taken to ratify a previous text. Texts may not be proposed in bad faith.

Once proposed, a text must undergo a two-hour ratification period. This period counts as part of a turn, and must be completed within the duration of the turn. During the ratification period, the turn cannot be willfully ended by any player: if the ratification period is not complete when the turn ends due to rule 315, the initial proposal is considered null and void, as per rule 325: future steps in the turn are skipped. The turn may not continue until the ratification period ends.

Once the two hour ratification period has elapsed, if a poll to ratify the proposed text (henceforth referred to as a "ratification poll") may be posted in nomic-official by any player if one has not already been posted. Ratification polls lasts for three hours, and succeed if they receive unanimous votes for the ratification of the text or if all players who voted yea on the initial proposal vote yea on the ratification poll. If a ratification poll succeeds, the proposed text is ratified and adopted as if it were the text of the triggering rules change. 

If the ratification poll does not meet either of the two above conditions, it fails, and a new text may be proposed (beginning another ratification period), the triggering player may choose to treat the initial poll as a failure, or the player who proposed the initial proposal may propose a new proposal, as if their first proposal had been rendered null and void. This does not add any additional time in said player's turn. Regardless of the player's choice, they suffer a five point penalty in addition to any other penalties they might suffer.

The player who proposed the triggering proposal, and only that player, may propose a ratification poll in nomic-official at any time during the ratification period.

Ratification polls are not considered to be rules proposals and are unaffected by rules that regulate them, but are affected by rules that regulate polls in general; furthermore, they are unaffected by rules 335 and 328. Despite this, the entire ratification process, beginning when the initial proposal passes, is still considered to be part of step one of a turn as described in rule 306.

This rule takes priority over rules 336, 328, and all other rules pertaining to the ratification process.''',1),
    (339,'''A bet is specified by:  
an event, say E  
two players, A and B   
two positive integers a,b, with a <= 10 and b <= 10 

In such a bet, if event E occurs, then player A pays player B a points. Otherwise, if it does not occur, player B pays player A b points. For bets with more than two possible outcomes, any payout table agreed upon by both players is allowed (as long as all values are from -10 to 10). A player can initiate a bet during their turn as a turn action, and can accept other players' proposed bets at any time (as long as they don't already have one). In order for a bet to be valid, both parties must agree to the bet. Once it is agreed upon and accepted, it is now considered active until it is either resolved or cancelled. Each player can have at most one active bet at a time. It can be cancelled if 1) both players agree and 2) nothing that significantly impacts the probability of the event happening has happened since the bet started. 2) will be decided on a case by case basis by discussion if necessary. The outcome should be verifiable by a third party and should not be easily influenced by one of the participants.''',1),
    (345,'''This rule governs the properties of player-like automata, known henceforth as Dougs. Any Dougs added to the game in the future shall be added by amending this rule to add the Doug's stats to part D of this rule; any other rule establishing a Doug is null and void. However, other rules modifying the properties of Dougs function as normal. This rule takes priority over all other rules pertaining to Dougs. This rule also governs the properties of the Dougs established within it, and takes priority over all rules pertaining to their properties. Part D of this rule defers to all other parts of this rule. This rule, upon its adoption, establishes the game's first Doug, by granting Doug status to the Robber. It is structured as such:

   A. Constraint and self-definition clause (above)  
   B. Table of contents (this segment)  
   C. Traits of Dougs  
        i. Basic Doug Algorithm requirements  
        ii. Dougs and external processing  
        iii. Permissions of Dougs as player-like automata  
        iv. Dougs and points  
        v. Establishing Dougs  
   D. Established Dougs  
        i. The Robber  
   E. Additional notes 

Dougs have a place in turn order (chosen when they are established as if they just joined the server) and play the game according to an algorithm included in the portion of this rule establishing them. If a Doug's algorithm is unable to finish any step of a turn, that Doug is null and void and may not take turns. A Doug's algorithm must be deterministic. For instance, "The Doug proposes a new rule consisting of the text of a randomly selected xkcd comic" is acceptable, while "The Doug proposes a new rule with the text of an xkcd comic" is not. The section of this rule establishing a Doug must contain a name for the Doug.

Dougs cannot be players. Sentient beings cannot be Dougs, and may not influence a Doug's algorithm in any way other than executing a deterministic step. For instance, a sentient being could hit the "random" button on xkcd to select a comic for the Doug to use as its proposal's text, but a player may not choose of their own volition an xkcd comic for the Doug to upload. Any external processing required for a Doug's algorithm may be conducted by any player.

A Doug is treated as a player with the following caveats: if faced with a choice, the Doug always chooses the first available option that does not alter the gamestate, unless otherwise specified in its algorithm. If making any choice would alter the gamestate, the Doug randomly selects a player, and the game continues as if the selected player was the one facing the choice in the first place, unless otherwise specified by the Doug's algorithm. If a Doug is given a responsibility, such as being a Judge, that requires rational thought, the game instead continues as if the responsibility was always granted to the player before the Doug in turn order; this cannot be overridden by a Doug's algorithm. Dougs don't count as players for mechanics, such as Removal Votes, that care about a certain percentage of players. A Doug's algorithm can only cause it to vote on rules changes proposed by Dougs. Dougs may not invoke judgement.

Dougs acquire points by completing part III of a turn, and keep score and can win the game like any player. Dougs may have other ways of gaining or losing points, as established in their algorithm, or may gain and lose points in a wholly different way than players provided that they are still capable of completing their turn. The player who established a given Doug is responsible for keeping track of their Doug's score in #nomic-scores, unless the Doug is somehow capable of doing that itself.

Any time this rule is amended to establish a Doug, the amendment must take the form of another Doug added to the following list, with relevant the relevant data, numbered ordinally, formatted with its number and name, its position in the turn order, its algorithm, and any additional notes, with line breaks between. An amendment to this rule may do one, but not more, of the following: modify an established Doug, establish a new Doug, or amend non-Doug portions of this rule.

The established Dougs are:

Doug 001: The Robber (from Catan)  
The Robber, upon its establishment, shall enter the game at the end of the turn order.  
When the Robber takes its turn, it proposes transmuting the highest-numbered mutable rule to immutable. It allows exactly three hours of debate on this proposal, then posts the proposal's poll in #nomic-official. After that, it takes any turn actions that, in their rule, state that the Robber and/or Dougs take them, as well as challenging a randomly-selected player to a game of Balls, Dice, and Stickers as per rule 324, if able. This challenge functions as follows: the challenged player, if they accept, plays Balls, Dice, and Stickers on VC with their screen shared and at least one other player on the same VC. If the player reaches at least level 18, they win the challenge, with the associated point gain for themselves and point loss for the robber; otherwise, the Robber wins and gains the points, with the challenged player losing them. Then, the Robber rolls for points as normal. It does not roll an additional d6 for its vote succeeding unanimously. If the robber rolls a 1-3, it moves itself to a randomly selected player or Doug other than itself. The Robber votes yea on all proposals proposed by Dougs, including itself.  
Additional notes: the Robber cannot be moved to itself. Upon its establishment, the Robber keeps all points that it had in its non-Doug incarnation. The Robber does not lose points from failed proposals. This section of this rule defers priority to all other Robber-related rules.

Additional notes: LLMs are not sentient for the purposes of this rule. A Discord Bot may represent a Doug, but it may only be added to the server on the server admin's explicit go-ahead, which shall only be granted after it's made clear that the server welcomes the new bot and that the bot will not endanger the server. No Doug may interact in any way with the game Campaign for North Africa. Dougs ignore rule 335 for the purpose of voting on the proposals of other Dougs. Sentient players named or otherwise referred to as “Doug” are not considered Dougs, and Dougs named or otherwise referred to as “Player” are not considered players. If any action taken by a Doug would cause a situation in which further play is impossible, or if the legality of a move is impossible to determine with finality, or if by the Judge's best reasoning, not overruled, a move appears equally legal and illegal, then the Doug is no longer considered valid, the triggering action is rendered null and void, and the Doug's turn is skipped instead of the game ending.''',1),
    (346,'''This proposal governs rulings related to moving the Robber to another player via playing Boss Music.

* Person A is someone who has the robber. Person B is someone Person A is trying to give the robber to. "Human (non-Doug) Player" and "Person" are interchangeable within this rule.

* "**Boss Music** is any song or group of songs played during a boss fight.
     
     * A "**Boss Fight**" is a fight within a game (<:POV_you_lost_the_game:1289227580209106977>) of some kind against an enemy that is larger, stronger, and/or noticeably different in some other way from all other enemies in said game<:POV_you_lost_the_game:1289227580209106977> . Examples include Wheatley from Portal 2 and Jackenstein's <:YOUR_TAKING_TOO_LONG:1446237271551377519> Pumpkin from deltarune. These two are the default options, however players may choose whichever boss's music they desire (as long as it follows the rules).

* If Person B gave Person A the robber *via this rule* then Person A may not give the robber to Person B *via this rule*.

* When Person A plays any segment of **Boss Music** for at least 2 seconds (that isn't silence), and Person B *and/or any third party in the same location (same room and within 8 ft of Person B) or VC as person B* can clearly hear the music, Person A gets a chance to give Person B the robber.

* Upon the segment reaching a playtime of 2 or more seconds, either person can send an apology in nomic-robber with the format "Apologies, (@Person)!" Parenthesis are not required, **however** punctuation *is*. If any player at any time in any channel sends a message with the format “Furfur, (@Person)”, no matter the punctuation, capitalization, and formatting, then they will immediately lose twenty points, have the robber placed on them, and have their next turn automatically skipped.

* If Person A noticeably sends the apology when they begin playing the audio, the robber will not move, and Person A loses 3 points while the robber gains 3 points.

* If Player A sends the apology first, then Player B receives the robber. When this happens, Player B loses one point and the robber gains one point.If Player B sends the apology first, then Player A becomes unable to give Player B the robber *via this rule* until losing it (either from waiting for it to disappear, by giving it to someone else, or by other legal robber shenanigans). When this happens, the robber gains three points.

* You may not give someone the robber if you do not have the robber.

* The pitch, speed, and other values of songs may be altered slightly, however must still be easily and instantly recognizable when played at the same time as the original, unedited version. This means that you cannot change the pitch too drastically nor alter the volume so that the song being played is **technically** able to be heard. If the identifiability of a music sample is disputed, this can be quickly judged (without the invoking of judgement) by playing the exact sample for a third, unrelated party and determining whether they can identify the song (or at least identify that it is boss music).All references to "@Person" in this rule represent pinging a player in this server, not actually sending a message with an @ symbol and the word Person unless Person is the username of a player in this server''',1),
]

cursor.executemany('INSERT INTO data (number, text, mutable) VALUES (?, ?, ?)', sample_data)

conn.commit()
conn.close()